apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-kubernetes-deployment
spec:
  selector:
    matchLabels:
      app: hello-world-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-kubernetes
    spec:
      containers:
      - name: hello-world-kubernetes-pod
        image: hello-world-kubernetes:1.0.0
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/ls 
            - /tmp/ready
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "250m"