apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-kubernetes-deployment
spec:
  selector:
    matchLabels:
      app: hello-world-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-kubernetes
    spec:
      containers:
      - name: hello-world-kubernetes-pod
        image: hello-world-kubernetes:1.0.0
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/ls 
            - /tmp/ready
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-kubernetes
  name: hello-world-kubernetes-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 32500
    nodePort: 32500
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-world-kubernetes

  