apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-kubernetes
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world-kubernetes
    spec:
      containers:
      - name: hello-world-kubernetes
        image: hello-world-kubernetes:1.0.0
        env:
        - name: ENV_CONFIG
          valueFrom:
            configMapKeyRef:
              name: 2nd env config
              key: ENV_CONFIG
        - name: ENV_SECRET
          valueFrom:
            secretKeyRef:
              name: 2nd env secret
              key: ENV_SECRET
        volumeMounts:
          - name: my-config
            mountPath: /usr/src/app/config
          - name: my-secret
            mountPath: /usr/src/app/secret
      volumes:
      - name: my-config
        configMap:
          name: my-config
      - name: my-secret
        secret:
          secretName: my-secret              