apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  ENV_CONFIG: 4th env config
---
apiVersion: v1    
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  ENV_SECRET: NHRoIGVudiBzZWNyZXQ=
