apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-kubernetes-deployment
  labels:
    name: hello-world-kubernetes-deployment
spec:
  selector:
    matchLabels:
      app: hello-world-kubernetes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world-kubernetes
    spec:
      containers:
      - name: hello-world-kubernetes-pod
        image: hello-world-kubernetes:1.0.2
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
            - /bin/ls 
            - /tmp/ready
          initialDelaySeconds: 2
          timeoutSeconds: 1
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-kubernetes-service
  labels:
    name: hello-world-kubernetes-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 32500
    nodePort: 32500
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-world-kubernetes

  