apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-kubernetes-configmap
  labels:
    name: hello-world-kubernetes-configmap  
data:
  ENV_CONFIG: 4th env config
---
apiVersion: v1    
kind: Secret
metadata:
  name: hello-world-kubernetes-secret
  labels:
    name: hello-world-kubernetes-secret   
type: Opaque
data:
  ENV_SECRET: NHRoIGVudiBzZWNyZXQ=
